site_name: DiagnoseHarmonise

theme:
  name: material

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Theory: Theory.md
  - Harmonisation Methods: HarmonisationMethods.md
  - Simulator: simulator.md
  - Terminal: terminal.md
  - API Reference:
      - DiagnosticReport: api/DiagnosticReport.md
      - HarmonisationFunctions: api/HarmonisationFunctions.md
      - DiagnosticFunctions: api/DiagnosticFunctions.md
      - PlotDiagnosticResults: api/PlotDiagnosticResults.md
      - LoggingTool: api/LoggingTool.md
      - DiagnosticFunctionsLong: api/DiagnosticFunctionsLong.md
      - CLI: api/CLI.md
      - Longitudinal CLI: api/LongitudinalCLI.md
      - GUI: api/GUI.md
      - GUI (Longitudinal): api/GUILongitudinal.md
      - Simulator: api/Simulator.md
      - SaveDiagnosticResults: api/SaveDiagnosticResults.md
      - Cross-sectional Workflow: api/CrossSectionalWorkflow.md
      - Longitudinal Workflow: api/LongitudinalWorkflow.md
      - Power Analysis: api/PowerAnalysis.md
      - "Demo: Run local priors": api/RunDemoLocalPriors.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            members_order: source
            show_source: false
            
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
